### ISSUE TITLE
Help setting up Kibana development environment

### ISSUE THREAD

**Issue by Amphagory** [lizozom/custom-kibana-theme#1]
I was looking to build on the work you have start with this plugin and ran into an issue loading it up in the Kibana 8.2 development environment.  While Kibana was running, I cloned your repo and copied it to the plugin folder in the Kibana repo and Kibana restarted due to the new files in the this folder.  Unfortunately, it didn't show the updates to the Kibana login or loading page logo and text when I navigate to localhost:5601.

Maybe 8.2 has change its scss since you have created this plugin? Maybe I need to do something more than just copy your repo into the plugin folder?

If I am correct, the login page scss file is https://github.com/elastic/kibana/blob/main/x-pack/plugins/security/public/authentication/login/login_page.scss.  This file hasn't changed for the last several revisions, therefore I assume I've "installed" improperly into the development environment.

Any ideas what I have done wrong? 

BTW: I have followed the getting stated instructions found here: https://www.elastic.co/guide/en/kibana/current/development-getting-started.html#development-getting-started and Elasticsearch and Kibana are running without any reported issues outputted to the console.

**Comment by lizozom** [comment]
I'm looking into this.

**Comment by lizozom** [comment]
@lukeelmers kindly helped with these instructions. Hope this helps.

- throw plugin code into kibana dev environment, run `yarn build`
- take zip file from build directory
- download fresh copy of `ES/Kibana` distributable (tested with 8.2.1)
- `bin/kibana-plugin install file:///Some/Path/customKibanaLogo-8.2.1.zip`
- `bin/elasticsearch`
- `bin/kibana`
- then i see kibana with the “whale tales” logo from the plugin

**Comment by Amphagory** [comment]
Oh, I know how to build a plugin and how to install it, that is clear in the documentation.
When I copied your plugin into the plugin folder, I excepted to see the changes in Kibana's development environment.
I was hoping to use the Kibana's development environment to see if my changes work as the changes should materialize immediately (from what I understand), instead of building a plugin and installing it to see if the changes worked.

I'll try again to get your plugin to work in Kibana's development environment, maybe I missed a step or something when I initial tried.

**Comment by Amphagory** [comment]
Update:  I got a little further in developing in the Kibana's development environment.  I seems changes do not show up automatically.  Although, it registers changes in the files with the plugin folder and rebuilds Kibana, I found out that you need to stop the environment and restart it with yarn start again.

When I restarted the environment:
1) Login page's logo and text did not change
2) Kibana loading logo and text changes only after a second, you still see the elastic logo and loading elastic for a few seconds every time
3) Kibana main logo change was successful

I'll try creating a plugin and installing it to see if the same results occur.

**Comment by Amphagory** [comment]
Update 2:  To build the plugin, it's better to use the [plugin-helpers](https://github.com/elastic/kibana/tree/8.2/packages/kbn-plugin-helpers).  Just run it in you plugin and when it ask for which version, make sure you input in the format: major.minor.patch (e.g. 8.2.0)

I have install the plugin into a fresh instance of Kibana 8.2.0 and it exhibits the same behaviour as in Kibana's development environment.

**Comment by lizozom** [comment]
> Kibana loading logo and text changes only after a second

Yes, unfortunatelly this a limitation as it takes the css a second to load.

**Comment by Amphagory** [comment]
I think we can close this issue and I'll open another one outlining the investigate / solutions I worked upon for the Login page's logo and text issue using version 8.2.0.

I have created a [PR ](https://github.com/lizozom/custom-kibana-logo/pull/3) with a two guides on how to set up the Kibana's development environment and build/install/remove plugins for others interested in added to your work.
