### ISSUE TITLE
Login page does not update with new logo and text

### ISSUE THREAD

**Issue by Amphagory** [lizozom/custom-kibana-theme#4]
I have tried this plugin in Kibana's development environment and creating a plugin and installing it to Kibana 8.2.0, but the login page does not update with new logo and text. (Does the login page logo and text display properly for you in version 8.2.0+?)

I thought something had change (like a change in the class name) so I was going to update the index.scss to reflex it, but that was not the case. 

In the last few version, the area of interest in file [login_page.tsx](https://github.com/elastic/kibana/blob/8.2/x-pack/plugins/security/public/authentication/login/login_page.tsx) in 8.2.0 [here](https://github.com/elastic/kibana/blob/183db6533a5800b53d327ed20575b11d937253ab/x-pack/plugins/security/public/authentication/login/login_page.tsx#L127) has not changed. 

Maybe I'm looking at the wrong file? Or maybe I'm doing something wrong again?  Looking for a bit of guidance.

**Comment by githubshirkevikas** [comment]
It didnt work for me as well. :(

Any help would be appreciated.

**Comment by lizozom** [comment]
@githubshirkevikas @Amphagory should be working now

**Comment by githubshirkevikas** [comment]
Thank you @lizozom. I will have look at it and let you know if it works for me as well. :)
